server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - "*"
      routes:
        - id: admin
          uri: lb://admin-manage
          predicates:
            - Path=/admin/**
        - id: system
          uri: lb://system-manage
          predicates:
            - Path=/system/**
        - id: activity
          uri: lb://activity-manage
          predicates:
            - Path=/activity/**