spring:
  application:
    name: auth-manage
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bigc_exhibition?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: localhost
    port: 6379
server:
  port: 8082